import pygame

CHANGE_SCENE = pygame.USEREVENT + 1
ASK_COLOR = pygame.USEREVENT + 2
TURN_TIMEOUT = pygame.USEREVENT + 3
CHANGE_SETTINGS = pygame.USEREVENT + 4
GAME_END = pygame.USEREVENT + 5
BOT_DRAW = pygame.USEREVENT + 6
BOT_DISCARD = pygame.USEREVENT + 7
